AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  SAM Template for sam-app

Globals:
  Function:
    Timeout: 10

Resources:
  ProcessOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: handler.lambda_handler
      Runtime: python3.8
      Events:
        SQSOrderEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrderQueue.Arn
            BatchSize: 10

  OrderQueue:
    Type: AWS::SQS::Queue

  OrderDb:
    Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

Outputs:
  ProcessOrderFunction:
    Description: "Process order Lambda Function ARN"
    Value: !GetAtt ProcessOrderFunction.Arn
  ProcessOrderFunctionIamRole:
    Description: "Implicit IAM Role created for process order function"
    Value: !GetAtt ProcessOrderFunctionRole.Arn
